## AIDS Dataset 

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import math

In [2]:
data=pd.read_csv("AIDS_Classification.csv")

In [3]:
data.head()

time  trt  age     wtkg  hemo  homo  drugs  karnof  oprior  z30  ...  str2  \
0   948    2   48  89.8128     0     0      0     100       0    0  ...     0   
1  1002    3   61  49.4424     0     0      0      90       0    1  ...     1   
2   961    3   45  88.4520     0     1      1      90       0    1  ...     1   
3  1166    3   47  85.2768     0     1      0     100       0    1  ...     1   
4  1090    0   43  66.6792     0     1      0     100       0    1  ...     1   

   strat  symptom  treat  offtrt  cd40  cd420  cd80  cd820  infected  
0      1        0      1       0   422    477   566    324         0  
1      3        0      1       0   162    218   392    564         1  
2      3        0      1       1   326    274  2063   1893         0  
3      3        0      1       0   287    394  1590    966         0  
4      3        0      0       0   504    353   870    782         0  

[5 rows x 23 columns]

In [4]:
data.isnull().sum()

time        0
trt         0
age         0
wtkg        0
hemo        0
homo        0
drugs       0
karnof      0
oprior      0
z30         0
preanti     0
race        0
gender      0
str2        0
strat       0
symptom     0
treat       0
offtrt      0
cd40        0
cd420       0
cd80        0
cd820       0
infected    0
dtype: int64

there is no null data to fill

In [5]:
X=data.iloc[:,:-1].values
y=data["infected"].values

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.2,random_state=1)

In [8]:
from sklearn.preprocessing import MinMaxScaler

In [10]:
X_train=MinMaxScaler().fit_transform(X_train)
X_test=MinMaxScaler().fit_transform(X_test)

## Random Forest Classification

In [11]:
from sklearn.ensemble import RandomForestClassifier

In [12]:
rfc=RandomForestClassifier()

In [13]:
rfc.fit(X_train,y_train)

RandomForestClassifier()

In [14]:
y_pred=rfc.predict(X_test)

## Check the accuracy and conf matrix

In [15]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [16]:
cm_rfc=confusion_matrix(y_pred,y_test)
cm_rfc

array([[293,  29],
       [ 16,  90]], dtype=int64)

In [17]:
accscore_rfc=accuracy_score(y_pred,y_test)
accscore_rfc

0.8948598130841121

## Naive Bayes

In [19]:
from sklearn.naive_bayes import GaussianNB

In [20]:
GaussianNB=GaussianNB()

In [21]:
GaussianNB.fit(X_train,y_train)

GaussianNB()

In [22]:
y_predGNB=GaussianNB.predict(X_test)

In [23]:
cm_gnb=confusion_matrix(y_predGNB,y_test)
cm_gnb

array([[274,  47],
       [ 35,  72]], dtype=int64)

In [24]:
accscore_gnb=accuracy_score(y_predGNB,y_test)
accscore_gnb

0.8084112149532711

## KNN

In [25]:
from sklearn.neighbors import KNeighborsClassifier

In [36]:
knn=KNeighborsClassifier(n_neighbors=3)

In [37]:
knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [38]:
y_pred_knn=knn.predict(X_test)

In [39]:
cm_knn=confusion_matrix(y_pred_knn,y_test)
cm_knn

array([[291,  64],
       [ 18,  55]], dtype=int64)

In [40]:
accscore_knn=accuracy_score(y_pred_knn,y_test)
accscore_knn

0.8084112149532711

## Grid Search

In [41]:
from sklearn.model_selection import  GridSearchCV

param_grid = {
    'n_neighbors': range(1, 31),
    'weights': ['uniform', 'distance'],
    'metric': ['euclidean', 'manhattan', 'minkowski']
}

In [42]:
grid_search = GridSearchCV(knn, param_grid, cv=5, scoring='accuracy')

In [43]:
grid_search.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(n_neighbors=3),
             param_grid={'metric': ['euclidean', 'manhattan', 'minkowski'],
                         'n_neighbors': range(1, 31),
                         'weights': ['uniform', 'distance']},
             scoring='accuracy')

In [44]:
print(f"Best params: {grid_search.best_params_}")
print(f"Best accuracy score: {grid_search.best_score_}")

Best params: {'metric': 'euclidean', 'n_neighbors': 6, 'weights': 'distance'}
Best accuracy score: 0.8240806096874842


In [46]:
from sklearn.metrics import classification_report

In [47]:
y_pred = grid_search.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.81      0.94      0.87       309
           1       0.73      0.43      0.54       119

    accuracy                           0.80       428
   macro avg       0.77      0.68      0.70       428
weighted avg       0.79      0.80      0.78       428



 knn classification not the one that I looking for. Random forest classification accuracy is better

In [48]:
data.describe().T

count        mean         std    min       25%       50%  \
time      2139.0  879.098177  292.274324   14.0  727.0000  997.0000   
trt       2139.0    1.520804    1.127890    0.0    1.0000    2.0000   
age       2139.0   35.248247    8.709026   12.0   29.0000   34.0000   
wtkg      2139.0   75.125311   13.263164   31.0   66.6792   74.3904   
hemo      2139.0    0.084151    0.277680    0.0    0.0000    0.0000   
homo      2139.0    0.661057    0.473461    0.0    0.0000    1.0000   
drugs     2139.0    0.131370    0.337883    0.0    0.0000    0.0000   
karnof    2139.0   95.446470    5.900985   70.0   90.0000  100.0000   
oprior    2139.0    0.021973    0.146629    0.0    0.0000    0.0000   
z30       2139.0    0.550257    0.497584    0.0    0.0000    1.0000   
preanti   2139.0  379.175783  468.657526    0.0    0.0000  142.0000   
race      2139.0    0.288453    0.453149    0.0    0.0000    0.0000   
gender    2139.0    0.827957    0.377506    0.0    1.0000    1.0000   
str2      2139.0    0.585788    0.492701    0.0    0.0000    1.0000   
strat     2139.0    1.979897    0.899053    1.0    1.0000    2.0000   
symptom   2139.0    0.172978    0.378317    0.0    0.0000    0.0000   
treat     2139.0    0.751286    0.432369    0.0    1.0000    1.0000   
offtrt    2139.0    0.362786    0.480916    0.0    0.0000    0.0000   
cd40      2139.0  350.501169  118.573863    0.0  263.5000  340.0000   
cd420     2139.0  371.307153  144.634909   49.0  269.0000  353.0000   
cd80      2139.0  986.627396  480.197750   40.0  654.0000  893.0000   
cd820     2139.0  935.369799  444.976051  124.0  631.5000  865.0000   
infected  2139.0    0.243572    0.429338    0.0    0.0000    0.0000   

                75%         max  
time      1091.0000  1231.00000  
trt          3.0000     3.00000  
age         40.0000    70.00000  
wtkg        82.5552   159.93936  
hemo         0.0000     1.00000  
homo         1.0000     1.00000  
drugs        0.0000     1.00000  
karnof     100.0000   100.00000  
oprior       0.0000     1.00000  
z30          1.0000     1.00000  
preanti    739.5000  2851.00000  
race         1.0000     1.00000  
gender       1.0000     1.00000  
str2         1.0000     1.00000  
strat        3.0000     3.00000  
symptom      0.0000     1.00000  
treat        1.0000     1.00000  
offtrt       1.0000     1.00000  
cd40       423.0000  1199.00000  
cd420      460.0000  1119.00000  
cd80      1207.0000  5011.00000  
cd820     1146.5000  6035.00000  
infected     0.0000     1.00000