In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data=pd.read_csv("lung_cancer_mortality_data_small.csv")

In [3]:
data.head()

id   age  gender   country diagnosis_date cancer_stage family_history  \
0   1  64.0    Male   Croatia     2016-04-05      Stage I            Yes   
1   2  50.0  Female     Italy     2023-04-20    Stage III             No   
2   3  65.0    Male  Slovakia     2023-04-05     Stage IV             No   
3   4  51.0  Female    Greece     2016-02-05    Stage III            Yes   
4   5  37.0  Female  Slovakia     2023-11-29    Stage III            Yes   

   smoking_status   bmi  cholesterol_level  hypertension  asthma  cirrhosis  \
0  Current Smoker  27.3                196             0       1          0   
1  Passive Smoker  22.4                234             1       1          1   
2   Former Smoker  20.2                210             0       0          0   
3    Never Smoked  41.8                262             1       0          1   
4  Passive Smoker  33.5                262             0       0          0   

   other_cancer treatment_type end_treatment_date  survived  
0             0      Radiation         2018-01-09         0  
1             0   Chemotherapy         2023-11-28         0  
2             0   Chemotherapy         2025-01-12         0  
3             0        Surgery         2016-11-14         0  
4             0   Chemotherapy         2025-03-10         0

id, country, diagnosis date,treatment date will be eliminated on this dataset to understand other factors effect on survival chance

In [4]:
data.drop("id",axis=1,inplace=True)

In [5]:
columnstodrop=["country","diagnosis_date","end_treatment_date"]
data=data.drop(columns=columnstodrop)

In [6]:
from sklearn.preprocessing import LabelEncoder

In [7]:
labenc=LabelEncoder()

In [8]:
data["gender"]=labenc.fit_transform(data["gender"])

In [9]:
data.head()

age  gender cancer_stage family_history  smoking_status   bmi  \
0  64.0       1      Stage I            Yes  Current Smoker  27.3   
1  50.0       0    Stage III             No  Passive Smoker  22.4   
2  65.0       1     Stage IV             No   Former Smoker  20.2   
3  51.0       0    Stage III            Yes    Never Smoked  41.8   
4  37.0       0    Stage III            Yes  Passive Smoker  33.5   

   cholesterol_level  hypertension  asthma  cirrhosis  other_cancer  \
0                196             0       1          0             0   
1                234             1       1          1             0   
2                210             0       0          0             0   
3                262             1       0          1             0   
4                262             0       0          0             0   

  treatment_type  survived  
0      Radiation         0  
1   Chemotherapy         0  
2   Chemotherapy         0  
3        Surgery         0  
4   Chemotherapy         0

In [10]:
data["cancer_stage"]=labenc.fit_transform(data["cancer_stage"])

In [11]:
data["family_history"]=labenc.fit_transform(data["family_history"])

In [12]:
data["smoking_status"]=labenc.fit_transform(data["smoking_status"])

In [13]:
data["treatment_type"]=labenc.fit_transform(data["treatment_type"])

In [14]:
data.head()

age  gender  cancer_stage  family_history  smoking_status   bmi  \
0  64.0       1             0               1               0  27.3   
1  50.0       0             2               0               3  22.4   
2  65.0       1             3               0               1  20.2   
3  51.0       0             2               1               2  41.8   
4  37.0       0             2               1               3  33.5   

   cholesterol_level  hypertension  asthma  cirrhosis  other_cancer  \
0                196             0       1          0             0   
1                234             1       1          1             0   
2                210             0       0          0             0   
3                262             1       0          1             0   
4                262             0       0          0             0   

   treatment_type  survived  
0               2         0  
1               0         0  
2               0         0  
3               3         0  
4               0         0

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
X=data.iloc[:,:-1].values
y=data["survived"].values

In [17]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=1)

In [18]:
from sklearn.preprocessing import StandardScaler

In [19]:
stdscal=StandardScaler()

In [20]:
X_train=stdscal.fit_transform(X_train)
X_test=stdscal.transform(X_test)

In [21]:
X_train

array([[-0.59492555, -0.99661288,  1.34538312, ...,  1.82568005,
         3.22932987, -1.33728364],
       [ 0.10541775,  1.00339863, -1.33839412, ...,  1.82568005,
        -0.30966177,  0.45017667],
       [ 0.50561392,  1.00339863, -0.44380171, ...,  1.82568005,
        -0.30966177,  0.45017667],
       ...,
       [-0.09468034, -0.99661288, -0.44380171, ...,  1.82568005,
         3.22932987, -0.44355349],
       [ 0.20546679, -0.99661288, -0.44380171, ..., -0.5477411 ,
        -0.30966177,  1.34390682],
       [ 1.90630052,  1.00339863, -0.44380171, ..., -0.5477411 ,
        -0.30966177, -1.33728364]])

## Random Forest Classifier

In [22]:
from sklearn.ensemble import RandomForestClassifier

In [23]:
randfor=RandomForestClassifier()

In [24]:
randfor.fit(X_train,y_train)

RandomForestClassifier()

In [25]:
y_pred_randfor=randfor.predict(X_test)

In [26]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [27]:
cm_randfor=confusion_matrix(y_pred_randfor,y_test)
cm_randfor

array([[8599, 2522],
       [  64,   15]], dtype=int64)

In [28]:
accscore_randfor=accuracy_score(y_pred_randfor,y_test)
accscore_randfor

0.7691071428571429

## Decision Tree Classifier

In [29]:
from sklearn.tree import DecisionTreeClassifier
dectree=DecisionTreeClassifier()

In [30]:
dectree.fit(X_train,y_train)

DecisionTreeClassifier()

In [31]:
y_pred_dectree=dectree.predict(X_test)

In [32]:
cm_dectree=confusion_matrix(y_pred_dectree,y_test)
cm_dectree

array([[6490, 1949],
       [2173,  588]], dtype=int64)

In [33]:
accscore_dectree=accuracy_score(y_pred_dectree,y_test)
accscore_dectree

0.6319642857142858

Decision Tree Classifier model not workin on this dataset well

## Naive Bayes

In [34]:
from sklearn.naive_bayes import GaussianNB

In [35]:
gss=GaussianNB()

In [36]:
gss.fit(X_train,y_train)

GaussianNB()

In [37]:
y_pred_gss=gss.predict(X_test)

In [38]:
cm_gss=confusion_matrix(y_pred_gss,y_test)
cm_gss

array([[8663, 2537],
       [   0,    0]], dtype=int64)

In [39]:
acc_gss=accuracy_score(y_pred_gss,y_test)
acc_gss

0.7734821428571429

naive bayes works better than forest models

## KNearest Neighbourhood Classifier

In [40]:
from sklearn.neighbors import KNeighborsClassifier

In [41]:
knn=KNeighborsClassifier(n_neighbors=5)

In [42]:
knn.fit(X_train,y_train)

KNeighborsClassifier()

In [43]:
y_pred_knn=knn.predict(X_test)

In [44]:
cm_knn=confusion_matrix(y_pred_knn,y_test)
cm_knn

array([[8031, 2333],
       [ 632,  204]], dtype=int64)

In [45]:
accscore_knn=accuracy_score(y_pred_knn,y_test)
accscore_knn

0.7352678571428571

#### Gaussian NB is better model on this dataset with %77 accuracy score.

## Grid Search

In [46]:
from sklearn.model_selection import GridSearchCV

In [56]:
hyper_params={"n_neighbors":np.arange(1,50)}
grid_search=GridSearchCV(estimator=knn,param_grid=hyper_params,scoring="accuracy",n_jobs=-1,cv=10)
grid_search

GridSearchCV(cv=10, estimator=KNeighborsClassifier(), n_jobs=-1,
             param_grid={'n_neighbors': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])},
             scoring='accuracy')

In [ ]:
grid_search.fit(X_train,y_train)