In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [5]:
data=pd.read_csv("Prostate_Cancer.csv")

In [7]:
data.head()

id diagnosis_result  radius  texture  perimeter  area  smoothness  \
0   1                M      23       12        151   954       0.143   
1   2                B       9       13        133  1326       0.143   
2   3                M      21       27        130  1203       0.125   
3   4                M      14       16         78   386       0.070   
4   5                M       9       19        135  1297       0.141   

   compactness  symmetry  fractal_dimension  
0        0.278     0.242              0.079  
1        0.079     0.181              0.057  
2        0.160     0.207              0.060  
3        0.284     0.260              0.097  
4        0.133     0.181              0.059

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   id                 100 non-null    int64  
 1   diagnosis_result   100 non-null    object 
 2   radius             100 non-null    int64  
 3   texture            100 non-null    int64  
 4   perimeter          100 non-null    int64  
 5   area               100 non-null    int64  
 6   smoothness         100 non-null    float64
 7   compactness        100 non-null    float64
 8   symmetry           100 non-null    float64
 9   fractal_dimension  100 non-null    float64
dtypes: float64(4), int64(5), object(1)
memory usage: 7.9+ KB


there is not a null object inside the database. so we dont need to drop or fill the missing values

In [14]:
data.describe().T

count       mean         std      min       25%       50%  \
id                 100.0   50.50000   29.011492    1.000   25.7500   50.5000   
radius             100.0   16.85000    4.879094    9.000   12.0000   17.0000   
texture            100.0   18.23000    5.192954   11.000   14.0000   17.5000   
perimeter          100.0   96.78000   23.676089   52.000   82.5000   94.0000   
area               100.0  702.88000  319.710895  202.000  476.7500  644.0000   
smoothness         100.0    0.10273    0.014642    0.070    0.0935    0.1020   
compactness        100.0    0.12670    0.061144    0.038    0.0805    0.1185   
symmetry           100.0    0.19317    0.030785    0.135    0.1720    0.1900   
fractal_dimension  100.0    0.06469    0.008151    0.053    0.0590    0.0630   

                       75%       max  
id                  75.250   100.000  
radius              21.000    25.000  
texture             22.250    27.000  
perimeter          114.250   172.000  
area               917.000  1878.000  
smoothness           0.112     0.143  
compactness          0.157     0.345  
symmetry             0.209     0.304  
fractal_dimension    0.069     0.097

we dont need to id coloumn inside the model and need to drop the "id"

In [17]:
data = data.drop(['id'], axis=1)

In [19]:
data.head()

diagnosis_result  radius  texture  perimeter  area  smoothness  compactness  \
0                M      23       12        151   954       0.143        0.278   
1                B       9       13        133  1326       0.143        0.079   
2                M      21       27        130  1203       0.125        0.160   
3                M      14       16         78   386       0.070        0.284   
4                M       9       19        135  1297       0.141        0.133   

   symmetry  fractal_dimension  
0     0.242              0.079  
1     0.181              0.057  
2     0.207              0.060  
3     0.260              0.097  
4     0.181              0.059

Successful drop

In [22]:
data['diagnosis_result'].replace({'M':0,'B':1},inplace=True)

In [24]:
data.head()

diagnosis_result  radius  texture  perimeter  area  smoothness  \
0                 0      23       12        151   954       0.143   
1                 1       9       13        133  1326       0.143   
2                 0      21       27        130  1203       0.125   
3                 0      14       16         78   386       0.070   
4                 0       9       19        135  1297       0.141   

   compactness  symmetry  fractal_dimension  
0        0.278     0.242              0.079  
1        0.079     0.181              0.057  
2        0.160     0.207              0.060  
3        0.284     0.260              0.097  
4        0.133     0.181              0.059

In [26]:
## data corelation matrix

corr_metrics = data.corr()
corr_metrics.style.background_gradient()

### fractial dimension and texture shows  a low coraltion and perimeter and area has strong corelation so I will eliminate that features

In [31]:
data = data.drop(['fractal_dimension', 'texture', 'perimeter'], axis=1)

In [33]:
data.head()

diagnosis_result  radius  area  smoothness  compactness  symmetry
0                 0      23   954       0.143        0.278     0.242
1                 1       9  1326       0.143        0.079     0.181
2                 0      21  1203       0.125        0.160     0.207
3                 0      14   386       0.070        0.284     0.260
4                 0       9  1297       0.141        0.133     0.181

In [35]:
from sklearn.model_selection import train_test_split

In [39]:
X=data.iloc[:,1:].values
X

array([[2.300e+01, 9.540e+02, 1.430e-01, 2.780e-01, 2.420e-01],
       [9.000e+00, 1.326e+03, 1.430e-01, 7.900e-02, 1.810e-01],
       [2.100e+01, 1.203e+03, 1.250e-01, 1.600e-01, 2.070e-01],
       [1.400e+01, 3.860e+02, 7.000e-02, 2.840e-01, 2.600e-01],
       [9.000e+00, 1.297e+03, 1.410e-01, 1.330e-01, 1.810e-01],
       [2.500e+01, 4.770e+02, 1.280e-01, 1.700e-01, 2.090e-01],
       [1.600e+01, 1.040e+03, 9.500e-02, 1.090e-01, 1.790e-01],
       [1.500e+01, 5.780e+02, 1.190e-01, 1.650e-01, 2.200e-01],
       [1.900e+01, 5.200e+02, 1.270e-01, 1.930e-01, 2.350e-01],
       [2.500e+01, 4.760e+02, 1.190e-01, 2.400e-01, 2.030e-01],
       [2.400e+01, 7.980e+02, 8.200e-02, 6.700e-02, 1.530e-01],
       [1.700e+01, 7.810e+02, 9.700e-02, 1.290e-01, 1.840e-01],
       [1.400e+01, 1.123e+03, 9.700e-02, 2.460e-01, 2.400e-01],
       [1.200e+01, 7.830e+02, 8.400e-02, 1.000e-01, 1.850e-01],
       [1.200e+01, 5.780e+02, 1.130e-01, 2.290e-01, 2.070e-01],
       [2.200e+01, 6.590e+02, 1.140e-01,

In [41]:
y=data.iloc[:,0].values
y

array([0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0], dtype=int64)

In [43]:
X_train, X_test, y_train, y_test= train_test_split(X,y,random_state=1,test_size=0.2)

## Logistic Regression Model

In [46]:
from sklearn.linear_model import LogisticRegression

In [48]:
logreg=LogisticRegression()

In [50]:
logreg.fit(X_train,y_train)

LogisticRegression()

In [52]:
y_pred_logreg=logreg.predict(X_test)

In [55]:
### accuracy calculation
from sklearn.metrics import confusion_matrix, accuracy_score
cm_logreg=confusion_matrix(y_test,y_pred_logreg)
cm_logreg

array([[11,  1],
       [ 3,  5]], dtype=int64)

In [57]:
acc_logreg=accuracy_score(y_test,y_pred_logreg)
acc_logreg

0.8

## KNN

In [60]:
from sklearn.neighbors import KNeighborsClassifier

In [62]:
knn=KNeighborsClassifier(n_neighbors=2)
knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=2)

In [64]:
y_pred_knn=knn.predict(X_test)

In [66]:
cm_knn=confusion_matrix(y_test,y_pred_knn)
cm_knn

array([[10,  2],
       [ 5,  3]], dtype=int64)

In [68]:
acc_knn=accuracy_score(y_test,y_pred_knn)
acc_knn

0.65

## Random Forest Classifier

In [71]:
from sklearn.ensemble import RandomForestClassifier

In [73]:
rfc=RandomForestClassifier()

In [75]:
rfc.fit(X_train,y_train)

RandomForestClassifier()

In [77]:
y_pred_rfc=rfc.predict(X_test)

In [79]:
cm_rfc=confusion_matrix(y_test,y_pred_rfc)
cm_rfc

array([[12,  0],
       [ 1,  7]], dtype=int64)

In [81]:
acc_rfc=accuracy_score(y_test,y_pred_rfc)
acc_rfc

0.95

In [83]:
### we have a strong prediction model in RFC but I wanna look the Decision Tree Model once

## Decision Tree Model

In [86]:
from sklearn.tree import DecisionTreeClassifier

In [88]:
dtc=DecisionTreeClassifier()

In [90]:
dtc.fit(X_train,y_train)

DecisionTreeClassifier()

In [92]:
y_pred_dtc=dtc.predict(X_test)

In [94]:
cm_dtc=confusion_matrix(y_test,y_pred_dtc)

In [96]:
cm_dtc

array([[9, 3],
       [1, 7]], dtype=int64)

In [98]:
acc_dtc=accuracy_score(y_test,y_pred_dtc)
acc_dtc

0.8

### in this dataset random forest classification model has the best prediction value. Since the database was too small, other models could not have much of an impact. If the database contained a little more data, we could expect a closer approach on other models.